config/routes.rb
Cen4010Scheduler::Application.routes.draw do

  devise_for :users

  get "home/index"

  resources :courses, :only => [:index]
  resources :course_requests

  resources :faculty_course_requests

  resources :reports, :only => [ :index, :destroy ]
  resources :course_reports, :only => [ :show, :new, :create ]
  resources :day_reports, :only => [ :show, :new, :create ]
  resources :time_reports, :only => [ :show, :new, :create ]
  resources :student_reports, :only => [ :show, :new, :create ]
  resources :faculty_reports, :only => [ :show, :new, :create ]

  namespace :admin do
    resources :users, :only => [ :show, :edit, :update, :index ]
    resources :courses, :only => [ :edit, :update, :index, :new, :create ]
  end

  root :to => 'courses#index'

end

app/models/course_request.rb
class CourseRequest < ActiveRecord::Base
  has_many :courses, :through => :course_request_courses
  has_many :course_request_courses
  belongs_to :user

  validates :user, :presence => true
  validates :season, :presence => true
  validates :year, :presence => true
  validates :course_request_courses, :length => { :in => 1..3 }
  validates_uniqueness_of :season, :scope => [ :year, :user_id, :type ]

  accepts_nested_attributes_for :course_request_courses, :reject_if => :all_blank, :allow_destroy => true

  def self.seasons
    [ 'Spring', 'Summer', 'Fall' ]
  end
end

app/controllers/course_requests_controller.rb
class CourseRequestsController < ApplicationController
  def new
    @course_request = CourseRequest.new
    3.times do
      @course_request.course_request_courses.build
    end
    respond_to do |format|
      format.html
    end
  end

  def create
    @course_request = CourseRequest.new(params[:course_request])
    @course_request.user = current_user

    if @course_request.save
      flash[:notice] = "Request submitted"
      redirect_to course_requests_path + "##{dom_id(@course_request)}"
    else
      render :action => "new"
    end
  end

  def show
    @course_request = CourseRequest.find_by_id_and_user_id(params[:id], current_user.id)
  end

  def index
    @course_requests = CourseRequest.find_all_by_user_id(current_user.id)
  end

  def edit
    @course_request = CourseRequest.find_by_id_and_user_id(params[:id], current_user.id)
    (3 - @course_request.course_request_courses.count).times do
      @course_request.course_request_courses.build
    end
  end

  def update
    @course_request = CourseRequest.find_by_id_and_user_id(params[:id], current_user.id)
    
    if @course_request.update_attributes(params[:course_request])
      flash[:notice] = "Request updated"
      redirect_to course_requests_path + "##{dom_id(@course_request)}"
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render :action => "edit"
    end
  end
end

app/views/course_requests/_course_fields.html.haml
.nested-fields
  = f.association :courses, :collection => Course.all
    

app/views/course_requests/_course_request.html.haml
.row{ :id => dom_id(course_request) }
  .span6
    %dl.dl-horizontal
      %dt
        Semester
      %dd= course_request.season
      %dt
        Year
      %dd= course_request.year
      %br
      %br
      %dd= link_to "Edit", edit_course_request_path(course_request), :class => 'btn btn-primary'

  .span6
    - course_request.course_request_courses.each do |req|
      %dl.dl-horizontal
        %dt
          Course
        %dd= req.course.full_name
        %dt
          Time
        %dd= req.time
        %dt
          Days
        %dd= req.day
        %dt
          Rank
        %dd= req.rank
        %br
.row
  .span12
    %hr.soften

app/views/course_requests/_course_request_row.html.haml
.row
  .span6
    %dl.dl-horizontal
      %dt
        Semester
      %dd= course_request.season
      %dt
        Year
      %dd= course_request.year

  .span6
    - course_request.course_request_courses.each do |req|
      %dl.dl-horizontal
        %dt
          Course
        %dd= req.course.full_name
        %dt
          Time
        %dd= req.time
        %dt
          Rank
        %dd= req.rank
        %br

app/views/course_requests/_form.html.haml
= simple_form_for(course_request) do |f|
  .row
    .span12
      = f.error_notification

  .row
    .span6
      = f.input :season, :as => :select, :collection => [ 'Spring', 'Summer', 'Fall' ], :label => "Semester"
      = f.input :year, :as => :select, :collection => (2012...2017)
    .span6
      = f.fields_for :course_request_courses do |crc_form|
        = crc_form.association :course, :collection => Course.all.map{ |course| [ course.full_name, course.id ] }
        = crc_form.input :time, :as => :select, :collection => CourseRequestCourse.times
        = crc_form.input :day, :as => :select, :collection => FacultyCourseRequest.fall_spring_days + FacultyCourseRequest.summer_days
        = crc_form.input :rank, :as => :radio_buttons, :collection => (1..3), :item_wrapper_class => 'inline'

  .row
    .span12
      .form-actions
        = f.button :submit, "Request Courses", :class => 'btn btn-primary btn-large'
        = link_to "Cancel", courses_path, :class => 'btn btn-large'

app/views/course_requests/edit.html.haml
.page-header
  %h1= "Edit Course Request"

= render :partial => 'form', :locals => { :course_request => @course_request }

app/views/course_requests/index.html.haml
.page-header
  = link_to new_course_request_path, :class => 'btn btn-primary' do
    %i.icon-plus.icon-white
    New Course Request
  %h1 My Course Requests

- if @course_requests.nil?
  %h3
    Looks like you don't have any course requests!

- else
  = render :partial => 'course_request', :collection => @course_requests

app/views/course_requests/new.html.haml
.page-header
  %h1= "New Student Course Request"

= render :partial => 'form', :locals => { :course_request => @course_request }

app/views/course_requests/show.html.haml
.page-header
  %h1= "Student Course Request: #{@course_request.season} #{@course_request.year}"

  - if @course_request.nil?
    %h3
      Sorry, we could not find a request with those parameters.

  - else
    = render @course_request