config/routes.rb
Cen4010Scheduler::Application.routes.draw do

  devise_for :users

  get "home/index"

  resources :courses, :only => [:index]
  resources :course_requests

  resources :faculty_course_requests

  resources :reports, :only => [ :index, :destroy ]
  resources :course_reports, :only => [ :show, :new, :create ]
  resources :day_reports, :only => [ :show, :new, :create ]
  resources :time_reports, :only => [ :show, :new, :create ]
  resources :student_reports, :only => [ :show, :new, :create ]
  resources :faculty_reports, :only => [ :show, :new, :create ]

  namespace :admin do
    resources :users, :only => [ :show, :edit, :update, :index ]
    resources :courses, :only => [ :edit, :update, :index, :new, :create ]
  end

  root :to => 'courses#index'

end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_filter :only_admin

  def index
    @courses = Course.all
  end

  def edit
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to admin_courses_path, notice: 'Course was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @course = Course.find(params[:id])
    
    if @course.update_attributes(params[:course])
      flash[:notice] = "Course updated"
      redirect_to admin_courses_path
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render :action => "edit"
    end
  end

  protected

  def only_admin
    redirect_to 'home/index' unless (user_signed_in? && current_user.is_admin)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @semester = "this semester"
    @semester = "#{params[:semester]} #{params[:year]}" if params[:semester] and params[:year]
    if params[:semester] and params[:year]
      @courses = Course.courses_for([ params[:semester], params[:year].to_i])
    else
      @courses = Course.courses_for( Course.semester_for( Date.today ) )
    end
  end

end

app/views/courses/index.html.haml
.page-header
  - if user_signed_in?
    - if current_user.is_student
      = link_to(new_course_request_path, :class => 'btn btn-primary') do
        %i.icon-plus.icon-white
        Request Courses
    - if current_user.is_faculty
      = link_to(new_faculty_course_request_path, :class => 'btn btn-primary') do
        %i.icon-plus.icon-white
        Request to Teach Courses
  %h1= "Courses for #{@semester}"

.row
  .span4
    = form_tag courses_path, :method => :get do
      = select_tag "year", options_for_select([ "2012", "2013", "2014", "2015"]), :id => 'year'
      %br/
      = select_tag "semester", options_for_select({ "Fall" => :fall, "Spring" => :spring }), :id => 'semester'
      %br/
      = submit_tag "View", :class => "btn btn-info"

  .span8
    %table#sorttable.table.table-bordered.tablesorter
      %thead
        %tr
          %th Identifier
          %th Name
          %th Degree Program
      %tbody
        - @courses.each do |c|
          %tr
            %td= c.identifier
            %td= c.name
            %td= c.degree_program.name