config/routes.rb
Cen4010Scheduler::Application.routes.draw do

  devise_for :users

  get "home/index"

  resources :courses, :only => [:index]
  resources :course_requests

  resources :faculty_course_requests

  resources :reports, :only => [ :index, :destroy ]
  resources :course_reports, :only => [ :show, :new, :create ]
  resources :day_reports, :only => [ :show, :new, :create ]
  resources :time_reports, :only => [ :show, :new, :create ]
  resources :student_reports, :only => [ :show, :new, :create ]
  resources :faculty_reports, :only => [ :show, :new, :create ]

  namespace :admin do
    resources :users, :only => [ :show, :edit, :update, :index ]
    resources :courses, :only => [ :edit, :update, :index, :new, :create ]
  end

  root :to => 'courses#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :report_users
  has_many :users, :through => :report_users
  belongs_to :user
  belongs_to :course

  validates :year, :presence => true
  validates :season, :presence => true
  validates :user, :presence => true
  
  default_scope :order => 'created_at DESC'

  # this method should be defined in every subclass of report
  after_save(:on => :create) do
    find_requests
  end

  def students
    report_users.map{ |u| u.user if u.request_type == 'CourseRequest' }.compact.uniq
  end

  def student_requests
    report_users.select{ |u| u.request_type == 'CourseRequest' }
  end

  def faculty
    report_users.map{ |u| u.user if u.request_type == 'FacultyCourseRequest' }.compact.uniq
  end

  def faculty_requests
    report_users.select{ |u| u.request_type == 'FacultyCourseRequest' }
  end

  def request_counts(attribute, requests)
    {}.tap do |counts|
      self.send(requests).each do |request|
        value = request.send(attribute)
        counts[value] = (counts[value].nil?) ? 1 : counts[value] += 1
      end
    end
  end

  def most_requested(attribute, requests)
    counts = request_counts(attribute, requests)

    largest = counts.values.sort.last

    result = counts.collect{ |value, count| value if count == largest }.compact
    if attribute == :course
      result = result.map{ |course| course.identifier }
    end
    result.join(', ')
  end

  def count_requests_by_time_and_course(request_type, time, course_id)
    ReportUser.count(:id, :conditions => [ 'request_type = ? AND time = ? AND course_id = ? AND report_id = ?', request_type, time, course_id, id ] )
  end

  def average_rank(request_type)
    ReportUser.average(:rank, :conditions => [ 'request_type = ? AND report_id = ?', request_type, id ] )
  end

  def average_course_rank(request_type, course_id)
    ReportUser.average(:rank, :conditions => [ 'request_type = ? AND course_id = ? AND report_id = ?', request_type, course_id, id ] )
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # DELETE /reports/1
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= simple_form_for(@report, :defaults => { :input_html => { :class => 'input-xxlarge' } }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :type
    = f.input :date_run
    = f.input :references
    = f.input :day
    = f.input :time

  .form-actions
    = f.button :submit, :class => "btn-primary"

app/views/reports/_header.html.haml
.row
  .span12
    %h2= "Report for #{report_for}"
    %h3= "#{report.season} #{report.year}"
    %h3= "Run #{report.date_run}"
    %hr

app/views/reports/_summary_table.html.haml
%table.table.table-condensed.table-bordered
  %thead
    %tr
      %th{:colspan => 2, :style => 'text-align: center;'}
        = title
  %tbody
    %tr
      %td.report-summary-label
        %h6 Day
      %td= format_summary day
    %tr
      %td.report-summary-label
        %h6 Time
      %td= format_summary time
    %tr
      %td.report-summary-label
        %h6 Average Rank
      %td= format_summary average_rank

app/views/reports/_user_table.html.haml
- if requests.empty?
  No requests.
-else 
  %table.table.table-bordered.tablesorter{ :id => id }
    %thead
      %th N Number
      %th Name
      %th Days
      %th Time
      %th Rank
    %tbody
      - requests.each do |request|
        %tr
          %td= request.user.n_number
          %td= "#{request.user.first_name} #{request.user.last_name}"
          %td= request.day
          %td= request.time
          %td= request.rank

app/views/reports/edit.html.haml
.page-header
  = link_to reports_path, :class => 'btn' do
    %i.icon-list-alt
    Back
  = link_to @report, :class => 'btn btn-primary' do
    %i.icon-info-sign.icon-white
    Show
  %h1 Editing report

= render 'form'

app/views/reports/index.html.haml
%div{ :style => 'float: right;' }
  .btn-group
    = link_to '#', :class => 'btn dropdown-toggle btn-primary', 'data-toggle' => 'dropdown' do
      New Report by...
      %span.caret

    %ul.dropdown-menu
      %li= link_to 'Course', new_course_report_path
      %li= link_to 'Day', new_day_report_path
      %li= link_to 'Time', new_time_report_path
      %li= link_to 'Students', new_student_report_path
      %li= link_to 'Faculty', new_faculty_report_path

%h1 Reports
.row
  .span12
    %table#reports_table.table.table-striped.tablesorter
      %thead
        %th{ :style => 'width: 30%;' } Date Run
        %th{ :style => 'width: 15%;' } Type
        %th{ :style => 'width: 15%;' } Owner
        %th{ :style => 'width: 20%;' } First Name
        %th{ :style => 'width: 20%;' } Last Name
      %tbody
        - @reports.each do |report|
          %tr
            %td
              = link_to( 'View', report, :class => 'btn btn-info btn-mini' )
              &nbsp;
              = report.created_at.strftime '%b %d, %Y %r'
            %td= report.type
            %td= report.user.n_number
            %td= report.user.last_name
            %td= report.user.first_name

app/views/reports/new.html.haml
.page-header
  = link_to reports_path, :class => 'btn' do
    %i.icon-list-alt
    Back
  %h1 New report

= render 'form'

app/views/reports/show.html.haml
.page-header
  = link_to reports_path, :class => 'btn' do
    %i.icon-list-alt
    Back
  = link_to edit_report_path(@report), :class => 'btn btn-primary' do
    %i.icon-pencil.icon-white
    Edit
  %h1 Listing reports

%dl
  %dt Type:
  %dd= @report.type
  %dt Date run:
  %dd= @report.date_run
  %dt References:
  %dd= @report.references
  %dt Day:
  %dd= @report.day
  %dt Time:
  %dd= @report.time