config/routes.rb
Cen4010Scheduler::Application.routes.draw do

  devise_for :users

  get "home/index"

  resources :courses, :only => [:index]
  resources :course_requests

  resources :faculty_course_requests

  resources :reports, :only => [ :index, :destroy ]
  resources :course_reports, :only => [ :show, :new, :create ]
  resources :day_reports, :only => [ :show, :new, :create ]
  resources :time_reports, :only => [ :show, :new, :create ]
  resources :student_reports, :only => [ :show, :new, :create ]
  resources :faculty_reports, :only => [ :show, :new, :create ]

  namespace :admin do
    resources :users, :only => [ :show, :edit, :update, :index ]
    resources :courses, :only => [ :edit, :update, :index, :new, :create ]
  end

  root :to => 'courses#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %title UNF Department of Computer Science
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}

    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{:data => {:toggle => "collapse", :target => ".nav-collapse"} }
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "CS Schedule", root_path, :class => "brand"
          .nav-collapse
            %ul.nav
              %li
                %a{:href => root_path} Home
              - if user_signed_in?
                - if current_user.is_student
                  %li= link_to "My Requests", course_requests_path
                - if current_user.is_faculty
                  %li= link_to "My Teaching Requests", faculty_course_requests_path
                - if current_user.is_admin or current_user.is_secretary
                  %li= link_to "Reports", reports_path
                - if current_user.is_admin
                  %li.dropdown
                    = link_to '#', :class => 'dropdown-toggle', 'data-toggle' => 'dropdown' do
                      Admin
                      %b.caret
                    %ul.dropdown-menu
                      %li= link_to 'Users', admin_users_path
                      %li= link_to 'Courses', admin_courses_path
                %li= link_to 'My Profile', edit_user_registration_path
                %li= link_to 'Logout', destroy_user_session_path, :method => :delete
              - else
                %li= link_to 'Login', new_user_session_path
                %li= link_to 'Sign Up', new_user_registration_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert #{name == :error ? "alert-error" : "alert-success" }" do
          %a.close{:href => "#", :data => {:dismiss => "alert"} } ×
          = msg
      = yield
      %hr
      %footer
        %p &copy; Company 2012